const data = {
  last_update: "2024-04-01",
  total_province: 34,
  provinces: [
    {
      provinsi: "Jakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jawa Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Banten",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Yogyakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bali",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Nusa Tenggara Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sumatera Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Lampung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kepulauan Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bangka Belitung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Papua",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Kalimantan Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Aceh",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Jambi",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Nusa Tenggara Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Papua Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Bengkulu",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Tenggara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Maluku",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Sulawesi Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Maluku Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      provinsi: "Gorontalo",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
  ],
};

export default data;
